"""
V2V BSD — AI Model Training Pipeline
=======================================
Trains an XGBoost classifier to predict blind spot alert levels from vehicle
telemetry features. Works as a hybrid system alongside the V3.0 math model:

  - Math Model (CRI): Physics-based, deterministic, interpretable
  - AI Model (XGBoost): Pattern-based, learns from simulation data
  - Hybrid: Both predictions shown on dashboard; AI validates math model

Training Data Source: bsd_metrics.csv (generated by v2v_bsd_simulation.py)

Usage:
    python train_ai_model.py              — Train on existing data
    python train_ai_model.py --collect     — Run simulation to collect data first
"""

import os
import sys
import json
import argparse
import numpy as np
import pandas as pd
from pathlib import Path

# Configure stdout to handle utf-8 safely in Windows terminals
if hasattr(sys.stdout, 'reconfigure'):
    sys.stdout.reconfigure(encoding='utf-8')

# ML Libraries
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
import xgboost as xgb
from joblib import dump, load


# ============================================================
# CONFIGURATION
# ============================================================
METRICS_FILE = "../Outputs/bsd_metrics.csv"
MODEL_FILE   = "../Outputs/bsd_xgboost_model.json"
ENCODER_FILE = "../Outputs/bsd_label_encoder.pkl"
REPORT_FILE  = "../Outputs/bsd_training_report.json"

# Features used for prediction (5-field BSM: accel/decel split)
FEATURE_COLS = [
    'speed',           # Ego speed (m/s) — BSM field 3
    'accel',           # Ego positive acceleration (m/s²) — BSM field 4
    'decel',           # Ego positive deceleration (m/s²) — BSM field 5
    'num_targets',     # Nearby V2V targets
    'max_gap',         # Closest target longitudinal gap (m)
    'rel_speed',       # Relative speed to closest threat target (m/s)
    'max_plr',         # Maximum PLR among active targets
    'k_lost_max',      # Max consecutive lost packets
]

# Adding derived features for better prediction
DERIVED_FEATURES = [
    'speed_kmh',       # Speed in km/h
    'abs_accel',       # |net_acceleration| = |accel - decel|
    'is_braking',      # decel > 1.0
    'brake_ratio',     # decel / max(speed, 0.1)
    'has_targets',     # num_targets > 0
    'speed_category',  # 0=slow, 1=medium, 2=fast
    'closing_speed',   # Equivalent to rel_speed
]

# NOTE: yaw_rate and signals are no longer in FEATURE_COLS.
# yaw_rate is derived from positions and not directly predictive.
# signals are not available in the 5-field BSM.

TARGET_COL = 'alert_level'  # What we predict: 0=SAFE, 1=CAUTION, 2=WARNING, 3=CRITICAL


def add_derived_features(df: pd.DataFrame) -> pd.DataFrame:
    """Add engineered features for better ML prediction (5-field BSM)."""
    df = df.copy()
    
    # Ensure decel column exists (backward compat with older CSVs)
    if 'decel' not in df.columns:
        df['decel'] = 0.0
        if 'accel' in df.columns:
            df['decel'] = df['accel'].clip(upper=0).abs()
            df['accel'] = df['accel'].clip(lower=0)
    
    df['speed_kmh'] = df['speed'] * 3.6
    net_accel = df['accel'] - df['decel']
    df['abs_accel'] = net_accel.abs()
    df['is_braking'] = (df['decel'] > 1.0).astype(int)
    df['brake_ratio'] = df['decel'] / df['speed'].clip(lower=0.1)
    df['has_targets'] = (df['num_targets'] > 0).astype(int)
    df['speed_category'] = pd.cut(df['speed'], bins=[-1, 5, 20, 100], labels=[0, 1, 2]).astype(int)
    if 'rel_speed' in df.columns:
        df['closing_speed'] = df['rel_speed']
    else:
        df['closing_speed'] = 0.0
    # Scenario flags (default 0 if column doesn't exist)
    if 'scenario_type' in df.columns:
        df['scenario_tsv'] = (df['scenario_type'] == 'TSV').astype(int)
        df['scenario_hnr'] = (df['scenario_type'] == 'HNR').astype(int)
    else:
        df['scenario_tsv'] = 0
        df['scenario_hnr'] = 0
    return df


def generate_critical_scenarios(n=300) -> pd.DataFrame:
    """Generate synthetic near-collision rows for the rare CRITICAL class to aid modeling."""
    np.random.seed(42)
    syn = pd.DataFrame({
        'speed': np.random.uniform(8, 20, n),
        'accel': np.random.uniform(0, 0.5, n),
        'decel': np.random.uniform(3, 8, n),
        'num_targets': np.random.randint(1, 4, n),
        'max_gap': np.random.uniform(0.1, 0.8, n),
        'rel_speed': np.random.uniform(5, 15, n),
        'max_plr': np.random.uniform(0, 0.15, n),
        'k_lost_max': np.random.randint(0, 2, n),
        'cri_left': np.random.uniform(0.82, 0.98, n),
        'cri_right': 0.0,
        'scenario_type': np.random.choice(['TSV', 'HNR', 'normal'], n)
    })
    # Basic derived features
    syn['speed_kmh'] = syn['speed'] * 3.6
    syn['abs_accel'] = syn['accel']
    syn['is_braking'] = 1
    syn['has_targets'] = 1
    syn['speed_category'] = 1
    syn['closing_speed'] = syn['rel_speed']
    syn['brake_ratio'] = syn['decel'] / np.maximum(syn['speed'], 0.1)
    syn['scenario_tsv'] = (syn['scenario_type'] == 'TSV').astype(int)
    syn['scenario_hnr'] = (syn['scenario_type'] == 'HNR').astype(int)
    return syn



def create_target_labels(df: pd.DataFrame):
    """
    Generate ground truth alerts that exactly match the Mathematical Model's CRI.
    This ensures the 'Model Sync %' measures the AI's ability to replicate the physics engine.
    """
    labels = pd.Series(0, index=df.index)
    
    # Use the maximum CRI from either side logged by the simulation
    # If column is missing or has NaN, treat as 0
    c_l = df['cri_left'].fillna(0.0) if 'cri_left' in df.columns else pd.Series(0.0, index=df.index)
    c_r = df['cri_right'].fillna(0.0) if 'cri_right' in df.columns else pd.Series(0.0, index=df.index)
    c = np.maximum(c_l, c_r)
    
    # Standard BSD Thresholds
    labels[c >= 0.3] = 1 # CAUTION
    labels[c >= 0.6] = 2 # WARNING
    labels[c >= 0.8] = 3 # CRITICAL
    
    return labels


def get_class_weights(y: pd.Series) -> dict:
    """
    Compute inverse-frequency class weights to handle imbalance.
    No data fabrication — XGBoost handles imbalance natively via scale_pos_weight.
    Returns dict of {class_int: weight} for use in sample_weight.
    """
    counts = y.value_counts()
    total = len(y)
    weights = {cls: total / (len(counts) * cnt) for cls, cnt in counts.items()}
    return weights


def train_model(df=None, model_out_path=MODEL_FILE, report_out_path=REPORT_FILE):
    """Train XGBoost model on simulation data."""
    print("=" * 70)
    print("🤖 V2V BSD — AI Model Training Pipeline")
    print("=" * 70)
    
    # ── Load Data ──
    if df is None:
        print(f"\n📂 Loading data from {METRICS_FILE}...")
        if not os.path.exists(METRICS_FILE):
            print("❌ No training data found! Run the simulation first:")
            print("   python v2v_bsd_simulation.py --no-gui --steps 3600")
            sys.exit(1)
        df = pd.read_csv(METRICS_FILE)
    print(f"   Loaded {len(df)} rows, {df['ego_vid'].nunique() if 'ego_vid' in df.columns else 'synthetic'} unique vehicles")
    
    # ── Feature Engineering ──
    print("\n🔧 Engineering features...")
    df = add_derived_features(df)
    
    y_raw = create_target_labels(df)

    all_features = FEATURE_COLS + DERIVED_FEATURES
    available_features = [f for f in all_features if f in df.columns]
    X = df[available_features].copy()
    y = y_raw.copy()

    print(f"   Features: {len(available_features)}")
    print(f"   Features: {available_features}")
    print(f"\n   Class distribution (labels from physics model intermediates):")
    label_names = {0: 'SAFE', 1: 'CAUTION', 2: 'WARNING', 3: 'CRITICAL'}
    for cls, count in y.value_counts().sort_index().items():
        print(f"     {label_names.get(cls, cls)}: {count}")

    # ── Train/Test Split ──
    print("\n   Performing stratified train/test split...")
    X_train_raw, X_test, y_train_raw, y_test = train_test_split(
        X, y, test_size=0.25, random_state=42, stratify=y
    )

    # Inject synthetic critical scenarios into TRAINING data only
    syn_df = generate_critical_scenarios(n=300)
    syn_df = add_derived_features(syn_df)
    syn_y = create_target_labels(syn_df)
    syn_X = syn_df[available_features].copy()
    X_train_raw = pd.concat([X_train_raw, syn_X], ignore_index=True)
    y_train_raw = pd.concat([y_train_raw, syn_y], ignore_index=True)
    print(f"   Injected 300 synthetic CRITICAL rows into training partition only")
    
    # ── SMOTE Oversampling ──
    print("\n⚖️  Applying SMOTE for rare classes...")
    from imblearn.over_sampling import SMOTE
    # Handle classes dynamically based on what's present but heavily oversample 1, 2, 3
    strat = {}
    total_train = len(y_train_raw)
    counts = y_train_raw.value_counts().to_dict()
    strat[1] = max(counts.get(1, 0), 3000)
    strat[2] = max(counts.get(2, 0), 2000)
    strat[3] = max(counts.get(3, 0), 500)
    
    smote = SMOTE(sampling_strategy=strat, random_state=42)
    X_train, y_train = smote.fit_resample(X_train_raw, y_train_raw)

    print("\n⚖️  Computing sample weights...")
    class_weights = get_class_weights(y_train)
    sample_weights = y_train.map(class_weights).fillna(1.0)
    
    print(f"   Train size: {len(X_train)}")
    print(f"   Test size: {len(X_test)} (stratified holdout, no synthetic injection)")
    
    print("\n🚀 Training XGBoost classifier...")
    model = xgb.XGBClassifier(
        n_estimators=200,
        max_depth=6,
        learning_rate=0.1,
        subsample=0.8,
        colsample_bytree=0.8,
        min_child_weight=3,
        gamma=0.1,
        reg_alpha=0.1,
        reg_lambda=1.0,
        objective='multi:softprob',
        num_class=4,
        eval_metric='mlogloss',
        random_state=42
    )
    
    model.fit(
        X_train, y_train,
        sample_weight=sample_weights,
        eval_set=[(X_test, y_test)],
        verbose=False,
    )
    print("   ✅ Training complete!")
    
    # ── Evaluate ──
    print("\n📊 Evaluation Results:")
    y_pred = model.predict_proba(X_test).argmax(axis=1)
    
    target_names = [label_names[i] for i in sorted(y_test.unique())]
    report = classification_report(y_test, y_pred, target_names=target_names, 
                                   output_dict=True, zero_division=0)
    report_str = classification_report(y_test, y_pred, target_names=target_names,
                                        zero_division=0)
    print(report_str)
    
    # ── CRITICAL class specific recall (the metric that matters most for safety) ──
    from sklearn.metrics import precision_score, recall_score
    crit_mask = (y_test == 3)
    if crit_mask.sum() > 0:
        p3 = precision_score(y_test, y_pred, labels=[3], average='micro', zero_division=0)
        r3 = recall_score   (y_test, y_pred, labels=[3], average='micro', zero_division=0)
        n3 = int(crit_mask.sum())
        print(f"\n⚠️  CRITICAL CLASS (label=3): Precision={p3:.4f}  Recall={r3:.4f}  Support={n3}")
        if r3 < 0.50:
            print("   ⛔ CRITICAL recall < 50% — model misses most imminent collisions.")
            print("   Run longer simulation to generate more CRITICAL samples.")
        elif r3 < 0.70:
            print("   ⚠️  CRITICAL recall below 70% — acceptable for early-stage, improvable.")
        else:
            print(f"   ✅ CRITICAL recall {r3:.1%} — strong detection of imminent collisions.")
    else:
        print("\n⚠️  No CRITICAL class samples in test set — run longer simulation first.")
    
    # ── Cross-Validation (TimeSeriesSplit) ──
    print("\n🔄 Running 5-fold TimeSeriesSplit cross-validation...")
    from sklearn.model_selection import TimeSeriesSplit
    from sklearn.metrics import accuracy_score, recall_score as rs, f1_score as f1s
    tscv = TimeSeriesSplit(n_splits=5)
    cv_accuracies, cv_crit_recalls, cv_f1_weighted = [], [], []
    # Run CV on the original (non-SMOTE) data to get unbiased estimates
    for fold_i, (train_idx, val_idx) in enumerate(tscv.split(X_train_raw)):
        X_cv_train, X_cv_val = X_train_raw.iloc[train_idx], X_train_raw.iloc[val_idx]
        y_cv_train, y_cv_val = y_train_raw.iloc[train_idx], y_train_raw.iloc[val_idx]
        cv_model = xgb.XGBClassifier(
            n_estimators=200, max_depth=6, learning_rate=0.1,
            objective='multi:softprob', num_class=4, eval_metric='mlogloss',
            random_state=42, verbosity=0
        )
        cv_model.fit(X_cv_train, y_cv_train, verbose=False)
        y_cv_pred = cv_model.predict(X_cv_val)
        cv_accuracies.append(accuracy_score(y_cv_val, y_cv_pred))
        cv_crit_recalls.append(rs(y_cv_val, y_cv_pred, labels=[3], average='micro', zero_division=0))
        cv_f1_weighted.append(f1s(y_cv_val, y_cv_pred, average='weighted', zero_division=0))
    cv_acc_arr = np.array(cv_accuracies)
    cv_cr_arr = np.array(cv_crit_recalls)
    cv_f1_arr = np.array(cv_f1_weighted)
    print(f"   CV Accuracy:       {cv_acc_arr.mean():.4f} ± {cv_acc_arr.std():.4f}")
    print(f"   CV CRITICAL Recall: {cv_cr_arr.mean():.4f} ± {cv_cr_arr.std():.4f}")
    print(f"   CV F1 (weighted):  {cv_f1_arr.mean():.4f} ± {cv_f1_arr.std():.4f}")
    # Holdout accuracy (primary model trained with SMOTE)
    holdout_acc = model.score(X_test, y_test)
    print(f"   Holdout Test Accuracy: {holdout_acc:.4f}")
    
    # Feature importance
    print("\n📈 Feature Importance:")
    
    # Use gain metric to match figure generation
    booster = model.get_booster()
    gain_dict = booster.get_score(importance_type='gain')
    total_gain = sum(gain_dict.values())
    if total_gain > 0:
        importances = {f: (gain_dict.get(f, 0.0) / total_gain) for f in available_features}
    else:
        importances = dict(zip(available_features, model.feature_importances_))
        
    sorted_imp = sorted(importances.items(), key=lambda x: x[1], reverse=True)
    for feat, imp in sorted_imp:
        bar = '█' * int(imp * 50)
        print(f"   {feat:20s} {imp:.4f} {bar}")
        
    imp_records = sorted_imp
    imp_df = pd.DataFrame(imp_records, columns=['feature', 'importance'])
    # Use report_out_path base directory to avoid overwriting production CSV during tests
    report_dir = Path(report_out_path).parent
    imp_path = report_dir / 'feature_importance.csv'
    imp_path.parent.mkdir(parents=True, exist_ok=True)
    imp_df.to_csv(imp_path, index=False)
    print(f"\n   Feature importances saved → {imp_path}")
    print(f"   Top 3 features: " + ", ".join(f"{r['feature']}={r['importance']:.3f}" for _, r in imp_df.head(3).iterrows()))
    
    # ── Save Model ──
    print(f"\n💾 Saving model to {model_out_path}...")
    model.save_model(model_out_path)
    
    # Save feature list for inference
    model_info = {
        'features': available_features,
        'label_map': label_names,
        'accuracy': float(holdout_acc),
        'cv_folds': 5,
        'cv_type': 'TimeSeriesSplit',
        'cv_accuracy_mean': float(cv_acc_arr.mean()),
        'cv_accuracy_std': float(cv_acc_arr.std()),
        'cv_critical_recall_mean': float(cv_cr_arr.mean()),
        'cv_critical_recall_std': float(cv_cr_arr.std()),
        'cv_f1_weighted_mean': float(cv_f1_arr.mean()),
        'cv_f1_weighted_std': float(cv_f1_arr.std()),
        'n_training_samples': len(X_train),
        'n_classes': len(y_train_raw.unique()),
        'feature_importance': {k: float(v) for k, v in importances.items()},
        'classification_report': report,
    }
    with open(report_out_path, 'w') as f:
        json.dump(model_info, f, indent=2)
    
    print(f"   Model saved: {model_out_path}")
    print(f"   Report saved: {report_out_path}")
    
    print("\n" + "=" * 70)
    print(f"✅ AI Model Training Complete!")
    print(f"   Holdout Accuracy:  {holdout_acc:.2%}")
    print(f"   CV Accuracy:       {cv_acc_arr.mean():.2%} ± {cv_acc_arr.std():.2%}")
    print(f"   CV CRITICAL Recall: {cv_cr_arr.mean():.2%} ± {cv_cr_arr.std():.2%}")
    print(f"   Classes: {list(label_names.values())}")
    print("=" * 70)
    
    return model


class BSDPredictor:
    """
    AI model wrapper for use in the simulation loop.
    Predicts alert levels from vehicle telemetry features.
    """
    
    def __init__(self, model_path: str = MODEL_FILE, report_path: str = REPORT_FILE):
        self.model = None
        self.features = None
        self.label_map = {0: 'SAFE', 1: 'CAUTION', 2: 'WARNING', 3: 'CRITICAL'}
        
        try:
            self.model = xgb.XGBClassifier()
            self.model.load_model(model_path)
            with open(report_path, 'r') as f:
                info = json.load(f)
            self.features = info.get('features', FEATURE_COLS + DERIVED_FEATURES)
            print(f"🤖 AI model loaded: {model_path}")
            print(f"   Accuracy: {info.get('accuracy', 'unknown'):.2%}")
        except FileNotFoundError:
            print(f"⚠️  AI model not found at {model_path}. Running without AI predictions.")
        except Exception as e:
            print(f"⚠️  Failed to load AI model: {e}")
    
    def predict(self, speed: float, accel: float, decel: float = 0.0,
                num_targets: int = 0, max_gap: float = 100.0, rel_speed: float = 0.0,
                max_plr: float = 0.0, k_lost_max: int = 0,
                yaw_rate: float = 0.0, signals: int = 0,
                target_angle: float = 0.0) -> dict:
        """
        Predict alert level from vehicle telemetry (5-field BSM compatible).
        
        Returns:
            dict with 'ai_alert' (str), 'ai_confidence' (float), 'ai_probs' (list)
        """
        if self.model is None:
            return {'ai_alert': 'N/A', 'ai_confidence': 0.0, 'ai_probs': []}
        
        net_accel = accel - decel
        row = {
            'speed': speed, 'accel': accel, 'decel': decel,
            'yaw_rate': yaw_rate,
            'num_targets': num_targets,
            'signals': signals,
            'max_gap': max_gap,
            'rel_speed': rel_speed,
            'max_plr': max_plr,
            'k_lost_max': k_lost_max,
            'speed_kmh': speed * 3.6,
            'abs_accel': abs(net_accel),
            'abs_yaw_rate': abs(yaw_rate),
            'is_braking': 1 if decel > 1.0 else 0,
            'is_signaling': 0,  # Not available in 5-field BSM
            'has_targets': 1 if num_targets > 0 else 0,
            'speed_category': 0 if speed < 5 else (1 if speed < 20 else 2),
            'closing_speed': rel_speed,
            'target_angle': target_angle,
            'brake_ratio': decel / max(speed, 0.1),
            'scenario_tsv': 0,
            'scenario_hnr': 0,
        }
        
        X = pd.DataFrame([{f: row.get(f, 0) for f in self.features}])
        
        try:
            probs = self.model.predict_proba(X)[0].tolist()
            pred = int(probs.index(max(probs)))
            confidence = max(probs)
            alert = self.label_map.get(pred, 'SAFE')
            crit_prob = probs[3] if len(probs) > 3 else 0.0
        except Exception:
            alert = 'N/A'
            confidence = 0.0
            probs = []
            crit_prob = 0.0
        
        return {
            'ai_alert': alert,
            'ai_confidence': confidence,
            'ai_probs': probs,
            'ai_critical_prob': crit_prob,
        }

    def batch_predict(self, feature_rows: list) -> list:
        """
        Batch predict for multiple vehicles in ONE XGBoost inference call.
        ~80x faster than calling predict() for each vehicle individually.
        
        Args:
            feature_rows: List of dicts, one per vehicle (keys = feature names)
        Returns:
            List of result dicts in same order as input
        """
        if self.model is None or not feature_rows:
            return [{'ai_alert': 'N/A', 'ai_confidence': 0.0, 'ai_critical_prob': 0.0}
                    for _ in feature_rows]
        try:
            # Match the derived feature logic in the single-predict() method
            processed_rows = []
            for r in feature_rows:
                s = r.get('speed', 0.0)
                a = r.get('accel', 0.0)
                d = r.get('decel', 0.0)
                net_a = a - d
                processed_row = r.copy()
                processed_row.update({
                    'speed_kmh': s * 3.6,
                    'abs_accel': abs(net_a),
                    'is_braking': 1 if d > 1.0 else 0,
                    'has_targets': 1 if r.get('num_targets', 0) > 0 else 0,
                    'speed_category': 0 if s < 5 else (1 if s < 20 else 2),
                    'closing_speed': r.get('rel_speed', 0.0),
                    'target_angle': r.get('target_angle', 0.0),
                    'brake_ratio': d / max(s, 0.1),
                    'scenario_tsv': r.get('scenario_tsv', 0),
                    'scenario_hnr': r.get('scenario_hnr', 0),
                })
                processed_rows.append({f: processed_row.get(f, 0) for f in self.features})
            
            X = pd.DataFrame(processed_rows)
            probs_matrix = self.model.predict_proba(X)  # shape: (N, 4)
            results = []
            for probs in probs_matrix:
                probs_list = probs.tolist()
                pred = int(probs.argmax())
                results.append({
                    'ai_alert':        self.label_map.get(pred, 'SAFE'),
                    'ai_confidence':   float(probs_list[pred]),
                    'ai_critical_prob': float(probs_list[3]) if len(probs_list) > 3 else 0.0,
                })
            return results
        except Exception as e:
            print(f"AI Batch Error: {e}")
            return [{'ai_alert': 'N/A', 'ai_confidence': 0.0, 'ai_critical_prob': 0.0}
                    for _ in feature_rows]

    def train(self, df: pd.DataFrame):
        self.model = train_model(df, model_out_path='test_model.json', report_out_path='test_report.json')
        self.features = FEATURE_COLS + DERIVED_FEATURES

BSDAIModel = BSDPredictor

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--collect", action="store_true", 
                        help="Run simulation to collect data before training")
    args = parser.parse_args()
    
    if args.collect:
        print("📡 Collecting training data via simulation...")
        import subprocess
        subprocess.run([sys.executable, "v2v_bsd_simulation.py", "--no-gui", "--steps", "3600"])
        print()
    
    train_model()
